### PR TITLE
segbot + ur5e basic integration

### PR DESCRIPTION
**Pull request by keke-220**

### CODE REVIEW

**Comment by keke-220** [comment]
@YoheiHayamizu why can't I see the old changes you made in this PR? Have you already corrected master_bu?

**Comment by YoheiHayamizu** [comment]
Yes, some changes have already been merged into the master_bu.

**Comment by keke-220** [comment]
> Yes, some changes have already been merged into the master_bu.

you mean the changes we found the other day have already been restored?

**Comment by YoheiHayamizu** [comment]
Wait, that looks strange. Let me check what's going on.

**Comment by YoheiHayamizu** [comment]
LGTM now

**Pull request merged**
